

source = ~/.config/hypr/startup.conf

$terminal = kitty
$fileManager = dolphin

source = ~/.config/hypr/keybinds.conf

input {
	kb_layout = ch
}

dwindle {
	preserve_split = yes
}

general {
	layout = master
	resize_on_border = true
	border_size = 0
}

master {
	mfact = 0.65
}

